"""Added picture column to tools

Revision ID: 4f646a4c4544
Revises: c5d48079abdb
Create Date: 2024-10-15 15:56:18.685652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f646a4c4544'
down_revision = 'c5d48079abdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
