"""empty message

Revision ID: 5fc7b9d92d50
Revises: 4f646a4c4544
Create Date: 2024-10-15 17:32:13.653267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fc7b9d92d50'
down_revision = '4f646a4c4544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_taken', sa.DateTime(), nullable=True),
    sa.Column('date_returned', sa.String(), nullable=True),
    sa.Column('tool_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('store_employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_tool_records_employee_id_employees')),
    sa.ForeignKeyConstraint(['store_employee_id'], ['store_employees.id'], name=op.f('fk_tool_records_store_employee_id_store_employees')),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('fk_tool_records_tool_id_tools')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('toolrecords')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toolrecords',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date_taken', sa.DATETIME(), nullable=True),
    sa.Column('date_returned', sa.VARCHAR(), nullable=True),
    sa.Column('tool_id', sa.INTEGER(), nullable=True),
    sa.Column('employee_id', sa.INTEGER(), nullable=True),
    sa.Column('store_employee_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='fk_toolrecords_employee_id_employees'),
    sa.ForeignKeyConstraint(['store_employee_id'], ['store_employees.id'], name='fk_toolrecords_store_employee_id_store_employees'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name='fk_toolrecords_tool_id_tools'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tool_records')
    # ### end Alembic commands ###
