"""Initial migration

Revision ID: c5d48079abdb
Revises: 
Create Date: 2024-10-15 15:19:52.571482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d48079abdb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('no_of_tools', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toolrecords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_taken', sa.DateTime(), nullable=True),
    sa.Column('date_returned', sa.String(), nullable=True),
    sa.Column('tool_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('store_employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_toolrecords_employee_id_employees')),
    sa.ForeignKeyConstraint(['store_employee_id'], ['store_employees.id'], name=op.f('fk_toolrecords_store_employee_id_store_employees')),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('fk_toolrecords_tool_id_tools')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toolrecords')
    op.drop_table('tools')
    op.drop_table('store_employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
