"""empty message

Revision ID: f6218305cb2b
Revises: 5fc7b9d92d50
Create Date: 2024-10-15 20:06:22.674276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6218305cb2b'
down_revision = '5fc7b9d92d50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_tools', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_column('available_tools')

    # ### end Alembic commands ###
